# Generated by Django 3.0.4 on 2020-03-24 13:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('funding_agency', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('direct_beneficiary', models.TextField()),
                ('documents', models.FileField(upload_to='')),
                ('project_report', multiselectfield.db.fields.MultiSelectField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually'), ('End Report', 'ER')], max_length=37)),
                ('assessment_evaluation', models.TextField()),
                ('audit', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
