# Generated by Django 3.0.4 on 2020-07-07 07:56

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'NGOs',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField()),
                ('direct_beneficiary', ckeditor.fields.RichTextField()),
                ('file1', models.FileField(blank=True, null=True, upload_to='documents')),
                ('file2', models.FileField(blank=True, null=True, upload_to='documents')),
                ('file3', models.FileField(blank=True, null=True, upload_to='documents')),
                ('file4', models.FileField(blank=True, null=True, upload_to='documents')),
                ('file5', models.FileField(blank=True, null=True, upload_to='documents')),
                ('project_report', multiselectfield.db.fields.MultiSelectField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually'), ('End Report', 'End Report')], max_length=37)),
                ('assessment_evaluation', models.TextField()),
                ('audit', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('funding_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.NGO')),
            ],
        ),
    ]
