# Generated by Django 3.0.4 on 2020-07-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='direct_beneficiary',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(max_length=500),
        ),
    ]
