# Generated by Django 3.0.4 on 2020-07-07 12:38

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200707_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='direct_beneficiary',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
