# Generated by Django 3.0.4 on 2020-03-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200326_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='documents',
            field=models.ImageField(blank=True, null=True, upload_to='documents'),
        ),
    ]
