# Generated by Django 3.0.4 on 2020-03-26 15:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200326_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='direct_beneficiary',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
