# Generated by Django 3.0.4 on 2020-04-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200326_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
