# Generated by Django 3.0.4 on 2020-04-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200404_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='documents',
            new_name='file1',
        ),
        migrations.AddField(
            model_name='project',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='project',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='project',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='project',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
