# Generated by Django 3.0.4 on 2020-04-14 07:02

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200404_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'NGOs',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='project_report',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually'), ('End Report', 'End Report')], max_length=37),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.NGO'),
        ),
    ]
