# Generated by Django 3.0.4 on 2020-04-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200414_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
