# Generated by Django 3.0.4 on 2020-03-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200311_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuptoken',
            name='expire',
            field=models.BooleanField(default=False),
        ),
    ]
