# Generated by Django 3.0.4 on 2020-03-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_signuptoken_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuptoken',
            name='expire',
        ),
    ]
