# Generated by Django 3.0.4 on 2020-03-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_signuptoken_expire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupToken',
        ),
    ]
